src/Components/Follower.jsx
src/Components/Header/HeaderWithClickBtn.jsx
src/Components/Header/HeaderWithMoreBtn.jsx
src/Components/Profile/Header.jsx
src/pages/Chat/Chat.jsx
src/pages/Chat/ChatTemplate.jsx
src/pages/Profile/Profile.jsx
src/pages/Profile/Setting.jsx
src/styles/theme.js

- Chat List를 만들고, 각 채팅방을 템플릿으로 컴포넌트화하였습니다.
- Follower 페이지에서 팔로우 버튼의 너비만 수정하였습니다. (진권님 담당이지만 제 화면에서 다르게 보여서 협의하 직접 수정)
- HeaderWithMoreBtn에서 페이지 타이틀을 입력할 prop 자리를 만들었습니다.

Chat/list UI 페이지 생성 및 마이너 컴포넌트 수정

---

src/Components/Chat/ChatMsgMe.jsx
src/Components/Chat/ChatMsgOther.jsx
src/Components/Header/HeaderWithClickBtn.jsx
src/Components/Header/HeaderWithMoreBtn.jsx
src/Components/UploadContent.jsx
src/Routes.js
src/pages/Chat/Chat.jsx
src/pages/Chat/ChatMsg.jsx
src/pages/Chat/ChatRoom.jsx

- 채팅방 구현, 채팅 리스트에서 항목 선택 시 라우터로 ``chat/:id`` 연결
- 채팅방에서 메시지 입력 시, 입력한 메시지 보여지도록 구현 (* 사진은 아직 미구현 상태)
- Header 내 뒤로가기 버튼 작동되도록 구현
- ``UploadContent.jsx``에서 입력창 위치 어긋나는 현상, 오타 수정

feat, refactory: 채팅방 구현, 라우터로 chat/:id 연결 및 기타 마이너 이슈 수정

---

src/Components/UploadContent.jsx
src/pages/Home/Home.jsx
src/pages/Post/Post.jsx
src/pages/Resistration/Resistration.jsx
src/pages/Upload/Upload.jsx

- 헤더 컴포넌트 스타일 수정 이후 발생한 css 이슈 해결 :
upload, post, resistration page에서 헤더와 메인섹션 간격 벌어진 문제 해결
- 업로드 페이지 네브바텀 삭제

Fix css/post,upload,resistraion

---

src/Components/Header/HeaderWithClickBtn.jsx
src/Components/Header/HeaderWithMoreBtn.jsx
src/pages/Profile/Profile.jsx

- goBack 기능 정상적으로 작동하도록 컴포넌트 수정, profile header 부분 교체

fix feature : goBack

---

src/Components/Search/SearchUserInfo.jsx
src/pages/Search/Search.jsx

검색시 공백 부분이 나타나지 않는 오류 수정

---

src/pages/Login/Login.jsx
src/pages/Login/Login.module.css

- 로그인 페이지 머지 후 발생한 이미지 ui 사이즈 문제 수정

로그인 페이지 머지 후 발생한 이미지 ui 사이즈 문제 수정

---

package-lock.json
package.json
src/pages/Login/LoginEmail.jsx
src/pages/Login/LoginMembership.jsx
yarn.lock

- 이메일로 로그인 영역에서 코드 리팩토링
- 회원가입 창에서 API 통신 코드 세팅

refactory: 이메일 로그인 코드 정리

---

src/Routes.js

에러나는 라우터 경로 수정

---

src/Components/Follower.jsx
src/Components/Profile/ProfileInfo.jsx
src/Components/Search/SearchUserInfo.jsx
src/Routes.js
src/pages/Followers/Followers.jsx
src/pages/Profile/Profile.jsx
src/pages/Search/Search.jsx

search api 연동 추가 작업

---

src/Components/Follower.jsx
src/Components/Profile/ProfileInfo.jsx
src/Routes.js
src/pages/Followers/Followings.jsx

profile API 적용

---

src/Components/Profile/Header.jsx
src/Components/Profile/ProfileInfo.jsx
src/Routes.js
src/pages/Follow/Followers.jsx
src/pages/Follow/Followings.jsx
src/pages/Profile/Profile.jsx
src/pages/Registration/Registration.jsx

- 본인 프로필 페이지일 경우 프로필 수정, 상품 등록 버튼 보이게 하기

profile api 연동 추가

---

src/Components/Follower.jsx
src/Components/Profile/Header.jsx
src/Components/Profile/ProfileInfo.jsx
src/Components/Profile/UserButton.jsx
src/Store.js
src/pages/Follow/Followers.jsx
src/pages/Login/LoginEmail.jsx
src/pages/Profile/Profile.jsx
src/pages/Profile/Setting.jsx
src/pages/Profile/SettingProfileEdit.jsx

- 프로필 수정 api 연동
- 프로필 수정을 위해 store 메소드 추가

프로필 수정 api 연동

---

src/Components/Feed.jsx
src/Components/Post/Comment.jsx
src/Components/Post/InputComment.jsx
src/Components/UserInfo.jsx
src/Routes.js
src/pages/Home/Home.jsx
src/pages/Post/Post.jsx

- Feed 이미지 선택하면 게시글로 가는 기능 구현 (API, Route)
- 게시글 내용 API에서 불러오는 기능 구현
- 게시글에 댓글 다는 기능 구현

feat: 게시글 보기, 댓글 작성 기능 구현

---

src/Components/Header/HeaderWithClickBtn.jsx
src/Components/Header/HeaderWithMoreBtn.jsx
src/Components/Profile/NowSales.jsx
src/Components/Profile/ProfileInfo.jsx
src/Components/UserInfo.jsx
src/pages/Profile/Profile.jsx
src/pages/Profile/Setting.jsx
src/pages/Profile/SettingProfileEdit.jsx
src/pages/Registration/Registration.jsx

- 프로필 피드 api 연동
(궁금한 사항들, 하면서 느낀 점 및 공유할 내용)
- 다른 사람의 프로필로 이동하여 피드를 보면 더보기, 하트, 댓글 아이콘들이 엑박이 뜨고있음
- api 명세서와 동일하게 작성했으나 422 클라이언트 에러로 인해 상품등록이 안되고 있음

프로필 api 연동

---

src/Components/Follower.jsx
src/pages/Follow/Followers.jsx
src/pages/Follow/Followings.jsx
src/pages/Registration/Registration.jsx

- 상품등록 api 연동
- 팔로워, 팔로잉 스크롤 css
(궁금한 사항들, 하면서 느낀 점 및 공유할 내용)

상품등록 api 연동

---

src/Components/Feed.jsx

- 복수의 이미지가 있는 게시글의 이미지를 슬라이드로 보이기
- 댓글 버튼을 누르면 해당 게시글로 이동

feat: 게시글 내 복수의 이미지 슬라이드로 보이기

---

src/Components/Feed.jsx
src/Components/ModalOption.jsx
src/Components/Post/Comment.jsx
src/pages/Post/Post.jsx

- 포스트 내 댓글 삭제 기능 구현
- 삭제는 작동하나, ``onClick()``에 삭제 기능이 담긴 함수를 넣었음에도 불구하고, 렌더링될 때 함수가 실행되는 문제 발생

댓글 삭제 기능 구현

---

src/Components/Post/Comment.jsx

렌더링시 팝업 이슈 해결

---

src/Components/Post/Comment.jsx
src/pages/Post/Post.jsx

새로고침 에러 수정

---

src/Components/Feed.jsx
src/Components/Upload/UploadContent.jsx
src/Components/Upload/UploadContentRework.jsx
src/Components/UserInfo.jsx
src/Routes.js
src/pages/Upload/UploadRework.jsx

게시물 삭제 에러 수정

---

src/Components/Feed.jsx
src/Components/Post/Comment.jsx
src/pages/Home/Home.jsx
src/pages/Post/Post.jsx
src/pages/Profile/Profile.jsx

- 댓글 작성자가 본인일 경우에만 '삭제' 보이기, 본인이 아닐 경우에는 '프로필 보기' 보이기
- [Fix] 이미지가 여러 개인 포스트에서 이동 버튼 위치 어긋나는 문제 수정
- 게시글 및 댓글의 작성시각을 현지(사용자)시각으로 변경
- 현재시각과 작성시각의 차이를 이용해, 자연스러운 메시지로 수정 (방금, 1시간 전, 1일 전 등)

Post, Comment 관련 페이지 수정

---

src/Routes.js
src/pages/Login/LoginMembership.jsx
src/pages/Login/Splash.jsx

- Splash 페이지 구현 및 웹 진입시 바로 보이도록 Route 변경
- 이메일 회원가입에서 '다음' 버튼을 눌러야 유효성 검사가 진행되는 점 리팩토링

Login feat/splash fix
